apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: library:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
